// app/layout.js

import "./globals.css";
import Footer from "@/component/Footer";
import Megamenu from "@/component/Megamenu";
import ClientLayoutWrapper from "@/component/ClientLayoutWrapper";
import { SpeedInsights } from "@vercel/speed-insights/next";



export const metadata = {
  title: "BullsEye",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const initialThemeScript = `
    (function() {
      try {
        const theme = localStorage.getItem('theme');
        const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
        if (theme === 'dark' || (!theme && prefersDark)) {
          document.documentElement.classList.add('dark');
        } else {
          document.documentElement.classList.remove('dark');
        }
      } catch (_) {}
    })();
  `;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: initialThemeScript }} />
         <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/Loopple/loopple-public-assets@main/motion-tailwind/motion-tailwind.css"/>
      </head>
      <body
        className="antialiased bg-white text-black dark:bg-gray-950 dark:text-white"
      >
        <Megamenu />
        <ClientLayoutWrapper>
          {children}
          <SpeedInsights />
        </ClientLayoutWrapper>
       
         <Footer />
        
      </body>
    </html>
  );
}

